import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/SideNav";
import TopBar from "@/components/navigation/TopNav";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose what you need
  variable: "--font-nunito-sans",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
  variable: "--font-nunito-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body
        className={`${nunitoSans.className} bg-white text-black max-w-[1920px] w-full mx-auto `}
      >
        <div className="flex">
          <Sidebar />
          <div className="flex-1">
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
